/**
 * This file is auto generated by tto v0.5.1 !
 * If you want to modify this code, please read the guide 
 * to modify code template.
 *
 * Get started: https://github.com/ixre/tto
 *
 * Copyright (C) 2009-2022 FZE.NET, All rights reserved.
 *
 * name : AxqStaff.java
 * author : jarrysix
 * date : 2022/10/18 14:03:28
 * description :
 * history :
 */

package com.github.ixre.tto.demo.entity;

import net.fze.util.TypeConv;
import java.math.BigDecimal;
import java.util.Date;

/** AxqStaff */
public class AxqStaff {
    private int id; // Id
    private int deptId; // DeptId
    private int jobId; // JobId
    private int isAdmin; // IsAdmin
    private Unknown type id:0 accessExtraJson; // AccessExtraJson
    private String username; // Username
    private String passwd; // Passwd
    private String nickname; // Nickname
    private String mobile; // Mobile
    private String avatar; // Avatar
    private int status; // 1->启用；2->禁用
    private int isDelete; // IsDelete
    private Date createTime; // CreateTime
    private Date updateTime; // UpdateTime
    private Date deleteTime; // DeleteTime
    
    
    public AxqStaff setId(int id){
        this.id = id;
        return this;
    }

    /** Id */
    public int getId() {
        return this.id;
    }
    
    public AxqStaff setDeptId(int deptId){
        this.deptId = deptId;
        return this;
    }

    /** DeptId */
    public int getDeptId() {
        return this.deptId;
    }
    
    public AxqStaff setJobId(int jobId){
        this.jobId = jobId;
        return this;
    }

    /** JobId */
    public int getJobId() {
        return this.jobId;
    }
    
    public AxqStaff setIsAdmin(int isAdmin){
        this.isAdmin = isAdmin;
        return this;
    }

    /** IsAdmin */
    public int getIsAdmin() {
        return this.isAdmin;
    }
    
    public AxqStaff setAccessExtraJson(Unknown type id:0 accessExtraJson){
        this.accessExtraJson = accessExtraJson;
        return this;
    }

    /** AccessExtraJson */
    public Unknown type id:0 getAccessExtraJson() {
        return this.accessExtraJson;
    }
    
    public AxqStaff setUsername(String username){
        this.username = username;
        return this;
    }

    /** Username */
    public String getUsername() {
        return this.username;
    }
    
    public AxqStaff setPasswd(String passwd){
        this.passwd = passwd;
        return this;
    }

    /** Passwd */
    public String getPasswd() {
        return this.passwd;
    }
    
    public AxqStaff setNickname(String nickname){
        this.nickname = nickname;
        return this;
    }

    /** Nickname */
    public String getNickname() {
        return this.nickname;
    }
    
    public AxqStaff setMobile(String mobile){
        this.mobile = mobile;
        return this;
    }

    /** Mobile */
    public String getMobile() {
        return this.mobile;
    }
    
    public AxqStaff setAvatar(String avatar){
        this.avatar = avatar;
        return this;
    }

    /** Avatar */
    public String getAvatar() {
        return this.avatar;
    }
    
    public AxqStaff setStatus(int status){
        this.status = status;
        return this;
    }

    /** 1->启用；2->禁用 */
    public int getStatus() {
        return this.status;
    }
    
    public AxqStaff setIsDelete(int isDelete){
        this.isDelete = isDelete;
        return this;
    }

    /** IsDelete */
    public int getIsDelete() {
        return this.isDelete;
    }
    
    public AxqStaff setCreateTime(Date createTime){
        this.createTime = createTime;
        return this;
    }

    /** CreateTime */
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public AxqStaff setUpdateTime(Date updateTime){
        this.updateTime = updateTime;
        return this;
    }

    /** UpdateTime */
    public Date getUpdateTime() {
        return this.updateTime;
    }
    
    public AxqStaff setDeleteTime(Date deleteTime){
        this.deleteTime = deleteTime;
        return this;
    }

    /** DeleteTime */
    public Date getDeleteTime() {
        return this.deleteTime;
    }
    

    
    public static AxqStaff createDefault(){
        AxqStaff dst = new AxqStaff();
        dst.setId(0);
        dst.setDeptId(0);
        dst.setJobId(0);
        dst.setIsAdmin(0);
        dst.setAccessExtraJson(Unknown type id:0);
        dst.setUsername("");
        dst.setPasswd("");
        dst.setNickname("");
        dst.setMobile("");
        dst.setAvatar("");
        dst.setStatus(0);
        dst.setIsDelete(0);
        dst.setCreateTime(new Date());
        dst.setUpdateTime(new Date());
        dst.setDeleteTime(new Date());
        return dst;
    }
}