/**
 * This file is auto generated by tto v0.5.1 !
 * If you want to modify this code, please read the guide 
 * to modify code template.
 *
 * Get started: https://github.com/ixre/tto
 *
 * Copyright (C) 2009-2022 FZE.NET, All rights reserved.
 *
 * name : AxqStaffLoginLogEntity.java
 * author : jarrysix
 * date : 2022/10/18 14:03:28
 * description :
 * history :
 */

package com.github.ixre.tto.demo.entity;

import net.fze.util.TypeConv;
import javax.persistence.Basic;
import javax.persistence.Id;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.GenerationType;
import javax.persistence.GeneratedValue;
import java.math.BigDecimal;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/** AxqStaffLoginLog */
@Entity
@Table(name = "axq_staff_login_log", schema = "")
public class AxqStaffLoginLogEntity {
    private Integer id; // Id
    private String username; // Username
    private String passwd; // Passwd
    private String ip; // Ip
    private Integer isDelete; // IsDelete
    private Date createTime; // CreateTime
    private Date updateTime; // UpdateTime
    private Date deleteTime; // DeleteTime
    
    
    public AxqStaffLoginLogEntity setId(int id){
        this.id = id;
        return this;
    }

    /** Id */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id" ,length = -1)
    public Integer getId() {
        return this.id;
    }
    
    public AxqStaffLoginLogEntity setUsername(String username){
        this.username = username;
        return this;
    }

    /** Username */
    @Basic
    @Column(name = "username", nullable = true ,length = 255)
    public String getUsername() {
        return this.username;
    }
    
    public AxqStaffLoginLogEntity setPasswd(String passwd){
        this.passwd = passwd;
        return this;
    }

    /** Passwd */
    @Basic
    @Column(name = "passwd", nullable = true ,length = 255)
    public String getPasswd() {
        return this.passwd;
    }
    
    public AxqStaffLoginLogEntity setIp(String ip){
        this.ip = ip;
        return this;
    }

    /** Ip */
    @Basic
    @Column(name = "ip", nullable = true ,length = 255)
    public String getIp() {
        return this.ip;
    }
    
    public AxqStaffLoginLogEntity setIsDelete(int isDelete){
        this.isDelete = isDelete;
        return this;
    }

    /** IsDelete */
    @Basic
    @Column(name = "is_delete", nullable = true ,length = -1)
    public Integer getIsDelete() {
        return this.isDelete;
    }
    
    public AxqStaffLoginLogEntity setCreateTime(Date createTime){
        this.createTime = createTime;
        return this;
    }

    /** CreateTime */
    @Basic
    @Column(name = "create_time", nullable = true ,length = -1)
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public AxqStaffLoginLogEntity setUpdateTime(Date updateTime){
        this.updateTime = updateTime;
        return this;
    }

    /** UpdateTime */
    @Basic
    @Column(name = "update_time", nullable = true ,length = -1)
    public Date getUpdateTime() {
        return this.updateTime;
    }
    
    public AxqStaffLoginLogEntity setDeleteTime(Date deleteTime){
        this.deleteTime = deleteTime;
        return this;
    }

    /** DeleteTime */
    @Basic
    @Column(name = "delete_time", nullable = true ,length = -1)
    public Date getDeleteTime() {
        return this.deleteTime;
    }
    


    /*
    public AxqStaffLoginLogEntity deep(){
        AxqStaffLoginLogEntity dst = new AxqStaffLoginLogEntity();
        
        dst.setId(this.getId());
        dst.setUsername(this.getUsername());
        dst.setPasswd(this.getPasswd());
        dst.setIp(this.getIp());
        dst.setIsDelete(this.getIsDelete());
        dst.setCreateTime(this.getCreateTime());
        dst.setUpdateTime(this.getUpdateTime());
        dst.setDeleteTime(this.getDeleteTime());
        return dst;
    }
    */

    /*
    public Map<String,Object> toMap(){
        Map<String,Object> mp = new HashMap<>();
        mp.put("id",this.id);
        mp.put("username",this.username);
        mp.put("passwd",this.passwd);
        mp.put("ip",this.ip);
        mp.put("isDelete",this.isDelete);
        mp.put("createTime",this.createTime);
        mp.put("updateTime",this.updateTime);
        mp.put("deleteTime",this.deleteTime);
        return mp;
    }
    */

    /*
    public static AxqStaffLoginLogEntity fromMap(Map<String,Object> data){
        AxqStaffLoginLogEntity dst = new AxqStaffLoginLogEntity();
        dst.setId(TypeConv.toInt(data.get("Id")));
        dst.setUsername(TypeConv.toString(data.get("Username")));
        dst.setPasswd(TypeConv.toString(data.get("Passwd")));
        dst.setIp(TypeConv.toString(data.get("Ip")));
        dst.setIsDelete(TypeConv.toInt(data.get("IsDelete")));
        dst.setCreateTime(TypeConv.toDateTime(data.get("CreateTime")));
        dst.setUpdateTime(TypeConv.toDateTime(data.get("UpdateTime")));
        dst.setDeleteTime(TypeConv.toDateTime(data.get("DeleteTime")));
        return dst;
    }
    */

    
    public static AxqStaffLoginLogEntity createDefault(){
        AxqStaffLoginLogEntity dst = new AxqStaffLoginLogEntity();
        dst.setId(0);
        dst.setUsername("");
        dst.setPasswd("");
        dst.setIp("");
        dst.setIsDelete(0);
        dst.setCreateTime(new Date());
        dst.setUpdateTime(new Date());
        dst.setDeleteTime(new Date());
        return dst;
    }
}