/**
 * This file is auto generated by tto v0.5.1 !
 * If you want to modify this code, please read the guide 
 * to modify code template.
 *
 * Get started: https://github.com/ixre/tto
 *
 * Copyright (C) 2009-2022 FZE.NET, All rights reserved.
 *
 * name : AxqStaffLoginLogServiceImpl.java
 * author : jarrysix
 * date : 2022/10/18 14:03:28
 * description :
 * history :
 */

package com.github.ixre.tto.demo.service.impl;

import com.github.ixre.tto.demo.entity.AxqStaffLoginLogEntity;
import com.github.ixre.tto.demo.repo.axq.AxqStaffLoginLogJpaRepository;
import com.github.ixre.tto.demo.service.axq.IAxqStaffLoginLogService;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.data.domain.Example;
import net.fze.common.infrastructure.PagingResult;
import net.fze.common.Standard;
import net.fze.util.Times;
import javax.inject.Inject;
import java.util.List;



/** AxqStaffLoginLog服务  */
@Service("axq_staff_login_log_service")
public class AxqStaffLoginLogServiceImpl implements IAxqStaffLoginLogService{
    @Inject
    private AxqStaffLoginLogJpaRepository repo;

    /** 查找AxqStaffLoginLog */
    @Override
    public AxqStaffLoginLogEntity findStaffLoginLogById(int id){
        return this.repo.findById(id).orElse(null);
    }

    /** 查找全部AxqStaffLoginLog */
    @Override
    public List<AxqStaffLoginLogEntity> findAllStaffLoginLog() {
        return this.repo.findAll();
    }

    /** 保存AxqStaffLoginLog */
    @Override
    public Error saveStaffLoginLog(AxqStaffLoginLogEntity e){
         return Standard.tryCatch(()-> {
            AxqStaffLoginLogEntity dst;
            if (e.getId() > 0) {
                dst = this.repo.findById(e.getId()).orElse(null);
                if(dst == null)throw new IllegalArgumentException("no such data");
            } else {
                dst = AxqStaffLoginLogEntity.createDefault();
                dst.setCreateTime(new java.util.Date());
            }
            dst.setUsername(e.getUsername());
            dst.setPasswd(e.getPasswd());
            dst.setIp(e.getIp());
            dst.setIsDelete(e.getIsDelete());
            dst.setDeleteTime(e.getDeleteTime());
            dst.setUpdateTime(new java.util.Date());
            dst = this.repo.save(dst);
            e.setId(dst.getId());
            return null;
          }).except(it->{
            it.printStackTrace();
            return null;
         }).error();
    }

    /** 根据对象条件查找 */
    @Override
    public AxqStaffLoginLogEntity findStaffLoginLogBy(AxqStaffLoginLogEntity o){
        return this.repo.findOne(Example.of(o)).orElse(null);
    }

    /** 根据对象条件查找 */
    @Override
    public List<AxqStaffLoginLogEntity> findStaffLoginLogListBy(AxqStaffLoginLogEntity o) {
        return this.repo.findAll(Example.of(o));
    }

    /** 根据条件分页查询 */
    @Override
    public PagingResult<AxqStaffLoginLogEntity> findPagingStaffLoginLog(AxqStaffLoginLogEntity o, Pageable page) {
        Page<AxqStaffLoginLogEntity> p = this.repo.findAll(Example.of(o),page);
        return new PagingResult<AxqStaffLoginLogEntity>(p.getContent(),p.getTotalElements());
    }

    /** 批量保存AxqStaffLoginLog */
    @Override
    public Iterable<AxqStaffLoginLogEntity> saveAllStaffLoginLog(Iterable<AxqStaffLoginLogEntity> entities){
        return this.repo.saveAll(entities);
    }

    /** 删除AxqStaffLoginLog */
    @Override
    public Error deleteStaffLoginLogById(int id) {
         return Standard.tryCatch(()-> {
             this.repo.deleteById(id);
             return null;
           }).except(it->{
            it.printStackTrace();
            return null;
         }).error();
    }

    /** 批量删除AxqStaffLoginLog */
    @Override
    public Error batchDeleteStaffLoginLog(List<Integer> id){
        return Standard.tryCatch(() -> {
            List<AxqStaffLoginLogEntity> all = this.repo.findAllById(id);
            this.repo.deleteInBatch(all);
            return null;
        }).except(it -> {
            it.printStackTrace();
            return null;
        }).error();
    }
}