/**
 * This file is auto generated by tto v0.5.1 !
 * If you want to modify this code, please read the guide 
 * to modify code template.
 *
 * Get started: https://github.com/ixre/tto
 *
 * Copyright (C) 2009-2022 FZE.NET, All rights reserved.
 *
 * name : IAxqStaffService.java
 * author : jarrysix
 * date : 2022/10/18 10:23:35
 * description :
 * history :
 */

package com.github.ixre.tto.demo.service.axq;

import com.github.ixre.tto.demo.entity.AxqStaffEntity;
import org.springframework.data.domain.Pageable;
import net.fze.common.infrastructure.PagingResult;

import java.util.List;



/** AxqStaff服务  */
public interface IAxqStaffService {
    /** 查找AxqStaff */
    AxqStaffEntity findStaffById(int id);

    /** 查找全部AxqStaff */
    List<AxqStaffEntity> findAllStaff();

    /** 保存AxqStaff */
    Error saveStaff(AxqStaffEntity e);

    /** 根据对象条件查找 */
    AxqStaffEntity findStaffBy(AxqStaffEntity o);

    /** 根据对象条件查找 */
    List<AxqStaffEntity> findStaffListBy(AxqStaffEntity o);

    /** 根据条件分页查询 */
    PagingResult<AxqStaffEntity> findPagingStaff(AxqStaffEntity o, Pageable page);

    /** 批量保存AxqStaff */
    Iterable<AxqStaffEntity> saveAllStaff(Iterable<AxqStaffEntity> entities);

    /** 删除AxqStaff */
    Error deleteStaffById(int id);

    /** 批量删除AxqStaff */
    Error batchDeleteStaff(List<Integer> id);
}