/**
 * This file is auto generated by tto v0.5.1 !
 * If you want to modify this code, please read the guide 
 * to modify code template.
 *
 * Get started: https://github.com/ixre/tto
 *
 * Copyright (C) 2009-2022 FZE.NET, All rights reserved.
 *
 * name : AxqStaffJpaRepository.java
 * author : jarrysix
 * date : 2022/10/18 10:23:35
 * description :
 * history :
 */

package com.github.ixre.tto.demo.repo;

import com.github.ixre.tto.demo.entity.AxqStaffEntity;
import org.springframework.data.jpa.repository.JpaRepository;

/** AxqStaff仓储接口 */
public interface AxqStaffJpaRepository extends JpaRepository<AxqStaffEntity, Integer>{
}