/**
 * This file is auto generated by tto v0.5.1 !
 * If you want to modify this code, please read the guide 
 * to modify code template.
 *
 * Get started: https://github.com/ixre/tto
 *
 * Copyright (C) 2009-2022 FZE.NET, All rights reserved.
 *
 * name : AxqStaffEntity.java
 * author : jarrysix
 * date : 2022/10/18 10:23:35
 * description :
 * history :
 */

package com.github.ixre.tto.demo.entity;

import jakarta.persistence.*;
import java.util.Date;

/** AxqStaff */
@Entity
@Table(name = "axq_staff", schema = "")
public class AxqStaffEntity {
    private Integer id; // Id
    private Integer deptId; // DeptId
    private Integer jobId; // JobId
    private Integer isAdmin; // IsAdmin
    private String username; // Username
    private String passwd; // Passwd
    private String nickname; // Nickname
    private String mobile; // Mobile
    private String avatar; // Avatar
    private Integer status; // 1->启用；2->禁用
    private Integer isDelete; // IsDelete
    private Date createTime; // CreateTime
    private Date updateTime; // UpdateTime
    private Date deleteTime; // DeleteTime
    
    
    public AxqStaffEntity setId(int id){
        this.id = id;
        return this;
    }

    /** Id */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id" ,length = -1)
    public Integer getId() {
        return this.id;
    }
    
    public AxqStaffEntity setDeptId(int deptId){
        this.deptId = deptId;
        return this;
    }

    /** DeptId */
    @Basic
    @Column(name = "dept_id", nullable = true ,length = -1)
    public Integer getDeptId() {
        return this.deptId;
    }
    
    public AxqStaffEntity setJobId(int jobId){
        this.jobId = jobId;
        return this;
    }

    /** JobId */
    @Basic
    @Column(name = "job_id", nullable = true ,length = -1)
    public Integer getJobId() {
        return this.jobId;
    }
    
    public AxqStaffEntity setIsAdmin(int isAdmin){
        this.isAdmin = isAdmin;
        return this;
    }

    /** IsAdmin */
    @Basic
    @Column(name = "is_admin", nullable = true ,length = -1)
    public Integer getIsAdmin() {
        return this.isAdmin;
    }


    public AxqStaffEntity setUsername(String username){
        this.username = username;
        return this;
    }

    /** Username */
    @Basic
    @Column(name = "username", nullable = true ,length = 255)
    public String getUsername() {
        return this.username;
    }
    
    public AxqStaffEntity setPasswd(String passwd){
        this.passwd = passwd;
        return this;
    }

    /** Passwd */
    @Basic
    @Column(name = "passwd", nullable = true ,length = 255)
    public String getPasswd() {
        return this.passwd;
    }
    
    public AxqStaffEntity setNickname(String nickname){
        this.nickname = nickname;
        return this;
    }

    /** Nickname */
    @Basic
    @Column(name = "nickname", nullable = true ,length = 255)
    public String getNickname() {
        return this.nickname;
    }
    
    public AxqStaffEntity setMobile(String mobile){
        this.mobile = mobile;
        return this;
    }

    /** Mobile */
    @Basic
    @Column(name = "mobile", nullable = true ,length = 255)
    public String getMobile() {
        return this.mobile;
    }
    
    public AxqStaffEntity setAvatar(String avatar){
        this.avatar = avatar;
        return this;
    }

    /** Avatar */
    @Basic
    @Column(name = "avatar", nullable = true ,length = 255)
    public String getAvatar() {
        return this.avatar;
    }
    
    public AxqStaffEntity setStatus(int status){
        this.status = status;
        return this;
    }

    /** 1->启用；2->禁用 */
    @Basic
    @Column(name = "status", nullable = true ,length = -1)
    public Integer getStatus() {
        return this.status;
    }
    
    public AxqStaffEntity setIsDelete(int isDelete){
        this.isDelete = isDelete;
        return this;
    }

    /** IsDelete */
    @Basic
    @Column(name = "is_delete", nullable = true ,length = -1)
    public Integer getIsDelete() {
        return this.isDelete;
    }
    
    public AxqStaffEntity setCreateTime(Date createTime){
        this.createTime = createTime;
        return this;
    }

    /** CreateTime */
    @Basic
    @Column(name = "create_time", nullable = true ,length = -1)
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public AxqStaffEntity setUpdateTime(Date updateTime){
        this.updateTime = updateTime;
        return this;
    }

    /** UpdateTime */
    @Basic
    @Column(name = "update_time", nullable = true ,length = -1)
    public Date getUpdateTime() {
        return this.updateTime;
    }
    
    public AxqStaffEntity setDeleteTime(Date deleteTime){
        this.deleteTime = deleteTime;
        return this;
    }

    /** DeleteTime */
    @Basic
    @Column(name = "delete_time", nullable = true ,length = -1)
    public Date getDeleteTime() {
        return this.deleteTime;
    }
    


    /*
    public AxqStaffEntity deep(){
        AxqStaffEntity dst = new AxqStaffEntity();
        
        dst.setId(this.getId());
        dst.setDeptId(this.getDeptId());
        dst.setJobId(this.getJobId());
        dst.setIsAdmin(this.getIsAdmin());
        dst.setAccessExtraJson(this.getAccessExtraJson());
        dst.setUsername(this.getUsername());
        dst.setPasswd(this.getPasswd());
        dst.setNickname(this.getNickname());
        dst.setMobile(this.getMobile());
        dst.setAvatar(this.getAvatar());
        dst.setStatus(this.getStatus());
        dst.setIsDelete(this.getIsDelete());
        dst.setCreateTime(this.getCreateTime());
        dst.setUpdateTime(this.getUpdateTime());
        dst.setDeleteTime(this.getDeleteTime());
        return dst;
    }
    */

    /*
    public Map<String,Object> toMap(){
        Map<String,Object> mp = new HashMap<>();
        mp.put("id",this.id);
        mp.put("deptId",this.deptId);
        mp.put("jobId",this.jobId);
        mp.put("isAdmin",this.isAdmin);
        mp.put("accessExtraJson",this.accessExtraJson);
        mp.put("username",this.username);
        mp.put("passwd",this.passwd);
        mp.put("nickname",this.nickname);
        mp.put("mobile",this.mobile);
        mp.put("avatar",this.avatar);
        mp.put("status",this.status);
        mp.put("isDelete",this.isDelete);
        mp.put("createTime",this.createTime);
        mp.put("updateTime",this.updateTime);
        mp.put("deleteTime",this.deleteTime);
        return mp;
    }
    */

    /*
    public static AxqStaffEntity fromMap(Map<String,Object> data){
        AxqStaffEntity dst = new AxqStaffEntity();
        dst.setId(TypeConv.toInt(data.get("Id")));
        dst.setDeptId(TypeConv.toInt(data.get("DeptId")));
        dst.setJobId(TypeConv.toInt(data.get("JobId")));
        dst.setIsAdmin(TypeConv.toInt(data.get("IsAdmin")));
        dst.setAccessExtraJson(TypeConv.toString(data.get("AccessExtraJson")));
        dst.setUsername(TypeConv.toString(data.get("Username")));
        dst.setPasswd(TypeConv.toString(data.get("Passwd")));
        dst.setNickname(TypeConv.toString(data.get("Nickname")));
        dst.setMobile(TypeConv.toString(data.get("Mobile")));
        dst.setAvatar(TypeConv.toString(data.get("Avatar")));
        dst.setStatus(TypeConv.toInt(data.get("Status")));
        dst.setIsDelete(TypeConv.toInt(data.get("IsDelete")));
        dst.setCreateTime(TypeConv.toDateTime(data.get("CreateTime")));
        dst.setUpdateTime(TypeConv.toDateTime(data.get("UpdateTime")));
        dst.setDeleteTime(TypeConv.toDateTime(data.get("DeleteTime")));
        return dst;
    }
    */

    
    public static AxqStaffEntity createDefault(){
        AxqStaffEntity dst = new AxqStaffEntity();
        dst.setId(0);
        dst.setDeptId(0);
        dst.setJobId(0);
        dst.setIsAdmin(0);
        dst.setUsername("");
        dst.setPasswd("");
        dst.setNickname("");
        dst.setMobile("");
        dst.setAvatar("");
        dst.setStatus(0);
        dst.setIsDelete(0);
        dst.setCreateTime(new Date());
        dst.setUpdateTime(new Date());
        dst.setDeleteTime(new Date());
        return dst;
    }
}