/**
 * This file is auto generated by tto v0.5.1 !
 * If you want to modify this code, please read the guide 
 * to modify code template.
 *
 * Get started: https://github.com/ixre/tto
 *
 * Copyright (C) 2009-2022 FZE.NET, All rights reserved.
 *
 * name : IAxqStaffLoginLogService.java
 * author : jarrysix
 * date : 2022/10/18 14:03:28
 * description :
 * history :
 */

package com.github.ixre.tto.demo.service;

import com.github.ixre.tto.demo.entity.AxqStaffLoginLogEntity;
import org.springframework.data.domain.Pageable;
import net.fze.common.infrastructure.PagingResult;

import java.util.List;



/** AxqStaffLoginLog服务  */
public interface IAxqStaffLoginLogService {
    /** 查找AxqStaffLoginLog */
    AxqStaffLoginLogEntity findStaffLoginLogById(int id);

    /** 查找全部AxqStaffLoginLog */
    List<AxqStaffLoginLogEntity> findAllStaffLoginLog();

    /** 保存AxqStaffLoginLog */
    Error saveStaffLoginLog(AxqStaffLoginLogEntity e);

    /** 根据对象条件查找 */
    AxqStaffLoginLogEntity findStaffLoginLogBy(AxqStaffLoginLogEntity o);

    /** 根据对象条件查找 */
    List<AxqStaffLoginLogEntity> findStaffLoginLogListBy(AxqStaffLoginLogEntity o);

    /** 根据条件分页查询 */
    PagingResult<AxqStaffLoginLogEntity> findPagingStaffLoginLog(AxqStaffLoginLogEntity o, Pageable page);

    /** 批量保存AxqStaffLoginLog */
    Iterable<AxqStaffLoginLogEntity> saveAllStaffLoginLog(Iterable<AxqStaffLoginLogEntity> entities);

    /** 删除AxqStaffLoginLog */
    Error deleteStaffLoginLogById(int id);

    /** 批量删除AxqStaffLoginLog */
    Error batchDeleteStaffLoginLog(List<Integer> id);
}