/**
 * This file is auto generated by tto v0.5.1 !
 * If you want to modify this code, please read the guide 
 * to modify code template.
 *
 * Get started: https://github.com/ixre/tto
 *
 * Copyright (C) 2009-2022 FZE.NET, All rights reserved.
 *
 * name : AxqStaffLoginLogJpaRepository.java
 * author : jarrysix
 * date : 2022/10/18 14:03:28
 * description :
 * history :
 */

package com.github.ixre.tto.demo.repo.axq;

import com.github.ixre.tto.demo.entity.AxqStaffLoginLogEntity;
import org.springframework.data.jpa.repository.JpaRepository;

/** AxqStaffLoginLog仓储接口 */
public interface AxqStaffLoginLogJpaRepository extends JpaRepository<AxqStaffLoginLogEntity, Integer>{
}